# Server configuration
host: "0.0.0.0"
port: 2222

# Timing configuration
min_delay: 0.1          # Minimum delay between data chunks
max_delay: 0.3          # Maximum delay between data chunks
initial_delay_range: [0.0, 0.5]  # Initial delay before sending data

# File paths
log_file: "connections.log"
db_file: "honeypot.db"
banners_file: "banners.txt"

# Banner mode: "normal", "gibberish", or "mixed"
mode: "mixed"
gibberish_length: 30

# Protocol settings
chunk_size: 1           # Bytes to send per chunk
max_bytes: null         # Maximum bytes to send (null = unlimited)

# Authentication settings
max_auth_attempts: 3    # Maximum authentication attempts per session
session_timeout: 300    # Session timeout in seconds

# Features
enable_fake_shell: true # Enable fake shell simulation after "auth"


# Report to AbuseIPDB
abuseipdb_api_key: "" # also schedule cron to run it daily, see docs

# Export to txt file for any blacklist
rbl_file: "last_7_days_ips.txt" # mount it or docker cp after creation
rbl_days_period: 7
