services:
  endlessh:
    build: .
    container_name: endlessh
    restart: unless-stopped
    ports:
      - "2222:2222" # 22 if not running real ssh service
    volumes:
      - ./config.yml:/home/endlessh/config.yml:ro
      - ./connections.log:/home/endlessh/connections.log
      - ./honeypot.db:/home/endlessh/honeypot.db
      - ./attack_data.json:/home/endlessh/attack_data.json
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    security_opt:
      - no-new-privileges:true
    networks:
      - endlessh-net
    mem_limit: 1g
    cpus: 1.0
    pids_limit: 20
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(2); s.connect(('localhost', 2222)); s.close()"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  endlessh-net:
    driver: bridge
